### ISSUE TITLE
Number of URLs submitting for Active/Passive Scan: 0

### ISSUE THREAD

**Issue by hardikrana437** [vmware/burp-rest-api#110]
**Describe the bug**
Number of URLs submitting for Active/Passive Scan: 0 even after passing url for scan

**To Reproduce**
1.burp-rest-api.bat
2.Navigate to http://localhost:8090/swagger-ui.html#/
2.Under POST
/burp/scanner/scans/active
Send a base url to Burp Scanner to perform active scan

**Expected behavior**
Number of URLs submitting for Active/Passive Scan>0

**Desktop (please complete the following information):**
 - OS: [ Windows]
 - Burp Suite _Professional_ version: Burp Suite Professional.2020.5
 - Extension **burp-rest-api** version  :2.1.0

**Comment by adracea** [comment]
Check out the URL you're submitting .
For example : if you add to scope and browse `https://www.google.com:443/test` , burp will index it as simply `https` + `www.google.com` as 443 would be the implicit default . When you start the scan , if you start it on `https://www.google.com:443/test` it will fail because of the extra `:443` .

**Comment by hardikrana437** [comment]
but 8090 is the port number at which my service is running. So i cant ignore that.

**Comment by ikkisoft** [comment]
@adracea was referring to the target host. Can you provide a step by step reproduction steps with screenshots?

Thanks,
L

**Comment by hardikrana437** [comment]
I haven't populated the sitemap with host url and directly including the host to scope and passing it for scan.
After populating the sitemap, my problem got fixed.
 Is this how functionality works, I first have to fill my sitemap?

**Comment by adracea** [comment]
@ikkisoft  Looking at the [code](https://github.com/vmware/burp-rest-api/blob/5d576d6f930c670568409e8249cef011f99b21bf/src/main/java/com/vmware/burp/extension/service/BurpService.java#L250) I think that if a sitemap is indeed 0 there might not be a scan happening ?
@hardikrana437  Usually you'd want to run a spider scan at least for show and after that run the active scan . That would populate the sitemap as needed .

**Comment by ikkisoft** [comment]
@adracea I see. I can propose the following change:

When a user sends an active scan request, we can first issue an HTTP request to the target URL and save it in the sitemap via `void addToSiteMap(IHttpRequestResponse item);`. Since active scans are supposed to send requests to the target anyway, sending an additional HTTP request seems reasonable to me.

Also, we can use this request to check whether the host is up or not. If no response, stop the scan.

What do you think? Let me know and I will prepare a PR.

**Comment by adracea** [comment]
@ikkisoft I think that would be good , doing a request beforehand and handling any possible exceptions could fix multiple "quirks" like : 
- DNS Entry not available - scans get stuck at 0% due to all items practically failing .
- Host not reachable for other reasons - same as above .
- The above mentioned issue where sitemap is 0 and host starts getting scanned thus getting stuck in a 0% loop .

Adding a `"Host not added because host was not reachable : ERRMESSAGE"` reply could fix some of the issues I've struggled with . 
I'm currently handling this behavior in my scripts but it would indeed be a nicer failsafe mechanism on the api's side .

**Comment by ikkisoft** [comment]
Fix in master.
