### ISSUE TITLE
Scan configurations not working for latest versions of burp

### ISSUE THREAD

**Issue by hardikrana437** [vmware/burp-rest-api#116]
Scan configurations not working for latest versions of burp

1. Post burp suite config 
2. Start Scan

**Expected behavior**
The scan should begin with that particular configuration but it is running with the default config.

Possible reason:
 We cannot currently set a default configuration for the Crawl and Audit in Burp Pro. So can we update the config at the very beginning of activeScan()?

**Comment by dinvlad** [comment]
For us, they don't even seem to be working on earlier versions (`1.7.22` at least): https://github.com/vmware/burp-rest-api/issues/92#issuecomment-705140125

**Comment by ikkisoft** [comment]
We confirmed that this issue is caused by the mismatch in the returned JSON object configuration between Burp 1.7 and Burp 2022.x

![Image Pasted at 2022-6-9 14-47](https://user-images.githubusercontent.com/6027823/172858565-96b2ac3b-9a73-4096-8178-390cda463418.png)

There is not much we can do here, since it's up to Portswigger to provide a clear and comprehensive APIs with legacy support. We will update the README to highlight the potential problems with certain Burp Rest API calls.

**Comment by AlessandroCotto** [comment]
This thread https://forum.portswigger.net/thread/scan-configuration-80c07e6d3e1080058 is exactly about this feature request "Updating scan configuration". 
No recent updates to the thread from PortSwigger yet
