### ISSUE TITLE
Authenticated scans

### ISSUE THREAD

**Issue by tristanlatr** [vmware/burp-rest-api#122]
Hi,

Is there a way to perform an authenticated scan ?

Thanks for your responses.

**Comment by adracea** [comment]
This is just an API wrapper over the API exposed by burp suite, I believe there currently isn't a way to configure a *scan* via the exposed APIs. 

In order to authenticate one would have to login via a test script that is run before the scan is executed and that would work as long as the session is allowed and/or updated via configured macros.

**Comment by ikkisoft** [comment]
As mentioned by @adracea, no magic here.

The newly introduced "recorded login" is not currently exposed by the Burp's API.
![Screen Shot 2021-02-24 at 19 44 50](https://user-images.githubusercontent.com/6027823/109049643-c8def300-76d8-11eb-8ed9-353e358ad823.png)

However, there're few options to perform authenticated scans:

- Instrument your app to use Burp/BurpRestApi, login and perform a scan using the same session
- Set the crawler configuration to autofill text / pwd fields using pre-defined values, and launch a crawling/scanning

**Comment by tristanlatr** [comment]
Thanks for the quick responses,

Test script + macros looks pretty complicated. 

What about this: https://portswigger.net/blog/burps-new-rest-api

Would is be possible to launch the scan with the "official" REST API (that supports username/password passed as REST API parameters). 

Then get the HTML report from your REST API plugin ?
