### ISSUE TITLE
[Questions] clear sitemap & spider with Chrome headless & export burp project

### ISSUE THREAD

**Issue by knassar702** [vmware/burp-rest-api#127]
hello team, thanks for this awesome project i've a small questions 

1. any clear sitemap option from the API?
2. any option for export burp project? 
3. spider works fine from your API but without Chrome headless that will make a problem with modern apps

regards

**Comment by ikkisoft** [comment]
1.  This project is exporting functionalities that are available in https://portswigger.net/burp/extender/api/. Clear sitemap is not available, but you could restart Burp with a clean state file

2. We're exposing `saveConfigAsJson` but not `saveState(java.io.File file)` since it's deprecated

3. Agree but the original scope of this extension was to expose original Burp's Extensibility. Since PortSwigger hasn't improved the extension APIs in years, the new Chrome headless spidering is not available for extensions

**Comment by knassar702** [comment]
hi @ikkisoft  thanks for your answer:), I've another question about the scanning Progress any options for getting the scanning progress of custom target ?
