### ISSUE TITLE
Cannot enter license key or accept EULA in Docker

### ISSUE THREAD

**Issue by rfernandezapML** [vmware/burp-rest-api#26]
Hello,

There is a problem when running this in Docker, you can't accept the EULA or enter your license key. This happens when using `gradlew bootRun`

I solved it by setting `standardInput = System.in` inside the bootRun block in build.gradle.

Hope this helps.

Regards.

**Comment by ajbr0wn** [comment]
I am also having this issue, but after setting `standardInput = System.in` in the bootRun block, it remained an issue...is there any other way to resolve this problem when running in Docker?

**Comment by 0xdevalias** [comment]
My solution was to run docker in a 'setup' mode the first time `docker run --rm -it foo/bar` so that I could manually enter those things. I also mapped the 'java preferences folder' out to my local system (or a volume) to persist the activation: `- ".java:/home/burp/.java"`
eg. https://github.com/ilyaglow/docker-burp/blob/master/docker-compose.yml#L6

**Comment by ajbr0wn** [comment]
This did eventually work for me by following the above suggestions.
