### ISSUE TITLE
Clear old issues without stopping server

### ISSUE THREAD

**Issue by ushyd201** [vmware/burp-rest-api#82]
Is there a way to clear old scanner issues without stopping the server?  This would be useful if the original issues are fixed and we would like to rerun the same scan to confirm the issues are gone.  Thanks!

**Comment by ikkisoft** [comment]
I agree, that would be great. Unfortunately, we're not exposing that functionality because there's not an elegant way of doing it in the Burp Extender APIs (https://portswigger.net/burp/extender/api/).

In the past, it was possible to reload a fresh state (see https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#restoreState(java.io.File)) but this API has been deprecated. 

I will leave it open as "feature request" even though it doesn't seem we have much control here.

**Comment by ikkisoft** [comment]
We've investigated this potential feature, but unfortunately it doesn't look like there is a Burp Suite API that we can leverage. The best I can suggest is to shutdown and restart the service.
